.TH "prj.cw/photo_editor Directory Reference" 3 "Photoeditor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prj.cw/photo_editor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBphoto_editors\&.cpp\fP"
.br
.RI "Файл \fBphoto_editors\&.cpp\fP, содержащий класс int \fBmain()\fP, в котором и реализовано приложение\&. "
.in -1c
