.TH "prj.cw/photo_editor/include/flags/flags.h" 3 "Photoeditor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prj.cw/photo_editor/include/flags/flags.h \- Файл flags\&.cpp, содержащий стрктуру \fBFlag\fP и флаги\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iosfwd>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFlag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Файл flags\&.cpp, содержащий стрктуру \fBFlag\fP и флаги\&. 


.PP
Definition in file \fBflags\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photoeditor from the source code\&.
