.TH "prj.cw/photo_editor/include/image/image.h" 3 "Photoeditor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prj.cw/photo_editor/include/image/image.h \- Файл \fBimage\&.h\fP, содержащий класс \fBImage\fP и его методы\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <opencv2/opencv\&.hpp>\fP
.br
\fR#include <string>\fP
.br
\fR#include <iosfwd>\fP
.br
\fR#include <GL/gl3w\&.h>\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "Класс \fBImage\fP для работы с изображениями\&. "
.ti -1c
.RI "struct \fBImage::MatDeleter\fP"
.br
.RI "Структура для освобождения памяти, занимаемой cv::Mat\&. "
.in -1c
.SH "Detailed Description"
.PP 
Файл \fBimage\&.h\fP, содержащий класс \fBImage\fP и его методы\&. 


.PP
Definition in file \fBimage\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photoeditor from the source code\&.
