.TH "C:/Users/knyaz_ayotgwn/source/repos/misis2023f-22-04-knyazev-a-p/prj.cw/photo_editor/photo_editors.cpp" 3 "PhotoEditor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/knyaz_ayotgwn/source/repos/misis2023f-22-04-knyazev-a-p/prj.cw/photo_editor/photo_editors.cpp \- Файл \fBphoto_editors\&.cpp\fP, содержащий класс int \fBmain()\fP, в котором и реализовано приложение\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <include/photoeditor/photo_editors\&.h>\fP
.br
\fR#include <include/image/image\&.h>\fP
.br
\fR#include <include/flags/flags\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Файл \fBphoto_editors\&.cpp\fP, содержащий класс int \fBmain()\fP, в котором и реализовано приложение\&. 


.SH "Function Documentation"
.PP 
.SS "int main ()"
Устанавливает версию OpenGL для контекста окна
.PP
Создает новое окно с заданными параметрами
.PP
Проверяет, было ли создание окна успешным
.PP
Создает новый экземпляр редактора с созданным окном
.PP
Получает доступ к объекту ввода/вывода ImGui
.PP
Устанавливает флаги окна ImGui 
.br
.PP
Создает новые экземпляры классов Flag и Image
.PP
Устанавливает фильтры файлов для диалоговых окон
.PP
Создает новую строку для хранения пути к файлу
.PP
Инициализирует флаги для управления параметрами и диалогами
.PP
glfwPollEvents опрашивает системные события
.PP
Подготавливает ImGui для нового кадра
.PP
Устанавливает следующую позицию окна ImGui
.PP
Устанавливает следующий размер окна ImGui
.PP
Создание окна ImGui
.PP
создаём меню-бар и кнопки для него
.PP
реализация горячих клавиш в приложении
.PP
создание диалогового окна для открытия изображения \&.jpg
.PP
реализовываем ползунки, для установки значений параметров изображений
.PP
реализовываем текстовые поля, для установки значений параметров изображений
.PP
реализация открытия изображения через диалоговое окно ImGuiFileDialog
.PP
Начинает модальное всплывающее окно под названием 'Notification(exit)'\&.
.PP
создание диалог\&. окна для сохранения изменённого изображения
.PP
Преобразуем локальное время в строку формата 'ГГГГ-ММ-ДД_чч-мм'\&.
.PP
Проверяем, были ли операция успешной и не отображается ли диалоговое окно для выбора папки\&. Если оба условия выполняются, то открывается всплывающее окно с сообщением о успешном сохранении\&.
.PP
Проверяем, была ли операция успешной\&. Если да, то открывается модальное всплывающее окно с сообщением о успешном сохранении\&.
.PP
Заканчиваем область окна, которую мы начали ранее\&.
.PP
Завершаем работу с библиотеками ImGui\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PhotoEditor from the source code\&.
