.TH "prj.cw/photo_editor/include/photoeditor/photo_editors.h" 3 "Photoeditor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prj.cw/photo_editor/include/photoeditor/photo_editors.h \- Файл \fBphoto_editors\&.h\fP, содержащий класс \fBEditor\fP и его методы\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include <iosfwd>\fP
.br
\fR#include 'imgui_impl_glfw\&.h'\fP
.br
\fR#include 'imgui_impl_opengl3\&.h'\fP
.br
\fR#include <glad/glad\&.h>\fP
.br
\fR#include <GLFW/glfw3\&.h>\fP
.br
\fR#include <GL/gl3w\&.h>\fP
.br
\fR#include <dialog/ImGuiFileDialog/ImGuiFileDialog\&.h>\fP
.br
\fR#include <opencv2/opencv\&.hpp>\fP
.br
\fR#include <string>\fP
.br
\fR#include <random>\fP
.br
\fR#include <ctime>\fP
.br
\fR#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGUI_DEFINE_MATH_OPERATORS\fP"
.br
.ti -1c
.RI "#define \fBGL_SILENCE_DEPRECATION\fP"
.br
.ti -1c
.RI "#define \fBUSE_IMGUI_TABLES\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Файл \fBphoto_editors\&.h\fP, содержащий класс \fBEditor\fP и его методы\&. 


.PP
Definition in file \fBphoto_editors\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define GL_SILENCE_DEPRECATION"

.PP
Definition at line \fB10\fP of file \fBphoto_editors\&.h\fP\&.
.SS "#define IMGUI_DEFINE_MATH_OPERATORS"

.PP
Definition at line \fB5\fP of file \fBphoto_editors\&.h\fP\&.
.SS "#define USE_IMGUI_TABLES"

.PP
Definition at line \fB11\fP of file \fBphoto_editors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photoeditor from the source code\&.
